# Используем Node.js как базовый образ
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package.json package-lock.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь проект
COPY . .

# !!!!! Собираем проект для продакшена !!!!!
RUN npm run build

# Открываем порт для Next.js
EXPOSE 443

# Команда запуска сервера в режиме продакшена
CMD ["npm", "run", "start"]