# Используем Node.js как базовый образ
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package.json package-lock.json ./

# Копируем весь проект
COPY . .

# Устанавливаем зависимости
RUN npm install

# Открываем порт для Next.js
EXPOSE 443

# Команда запуска сервера разработки
CMD ["npm", "run", "start"]