GET http://localhost:3000/api/users

GET http://localhost:3000/api/tasks

POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
  "email": "test1@mail.ru",
  "password": "123456"
}

###

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "test1@mail.ru",
  "password": "123456"
}

###

POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "name": "Testtodo",
  "description": "Testtodo description",
  "completed": false
}





